const restaurantNames = [
    "Urban Skillet",
    "BiG AL'S Pizzeria",
    "Tahini",
    "Fatimas Grill",
    "Adana Grill 🍽",
    "Humble Bean Cafe",
    "Utopia European Caffe",
    "Spice-C",
    "Ike's Love & Sandwiches",
    "Ma's House",
    "Daves Hot Chicken",
    "Dave's Hot Chicken",
    "The Halal Guys",
    "Istanbul Grill California",
    "Gourmet Burger",
    "Naz's Halal Food- Garden Grove",
    "Chili Chutney Afghani Restaurant",
    "Belacan Grill - Malaysian Bistro",
    "MASALA BAE",
    "MedMex Grill",
    "Khan Saab Desi Craft Kitchen",
    "Dave's Hot Chicken",
    "Hole in the Wall Burger",
    "Bundoo Khan",
    "Sofra Urbana",
    "YoYo Burgers and Chicken",
    "Bred's Nashville Hot Chicken - Anaheim Takeout",
    "Stark's Hot Chicken",
    "Ribs n Kabobs",
    "Simpang Asia - Venice",
    "Nomad Asian Bistro",
    "HotSpot Grill",
    "Anwar's Kitchen",
    "Lam's Thai and Chinese Restaurant",
    "Barnrau Thai Halal Cuisine",
    "Sana’s Indian Cuisine",
    "786 Degrees",
    "786 Degrees - Sapori",
    "Tikka Curry Bowls",
    "DönerG Mediterranean Grill-Santa Ana",
    "DonerG Turkish & Mediterranean Grill - Lake Forest",
    "Burger Boss",
    "Hatam Restaurant",
    "Hatam Restaurant",
    "Paratta",
    "Charo Chicken",
    "Halal House",
    "Dickey's Barbecue Pit",
    "World Famous Grill",
    "Humble Chef",
    "HiHo Cheeseburger",
    "Habibi Grill Halal Shawerma & Falafel",
    "Ameci Pizza & Pasta",
    "Mozambique",
    "Pita Pita",
    "I Can Barbecue Korean Grill",
    "Adonis Restaurant",
    "Wholesome Choice",
    "Anjappar Chettinad Indian Restaurant",
    "Curry Up Now",
    "Robina's Indian Cuisine",
    "Spice Plus Indian Restaurant & Grocery",
    "The Halal Guys",
    "Burger Boss",
    "Ma's House Chinese Islamic Restaurant",
    "Hayat's Kitchen",
    "Salomi Indian & Bangladeshi Restaurant",
    "Assam Indian kitchen",
    "Craft by Smoke and Fire",
    "Tahdig Tacos",
    "JERUSALEM CHICKEN",
    "Noodle St. Irvine",
    "Papi Tacos & Churros",
    "Dave's Hot Chicken",
    "Dave's Hot Chicken",
    "Dave's Hot Chicken",
    "Charminar Indian Restaurant & Catering",
    "Our Kitchen",
    "Xtra Cheese",
    "Ike's Love & Sandwiches",
    "Famous Tandoori",
    "House of Mandi - Yemeni Restaurant -مطعم بيت المندي اليمني",
    "Shish Taouk | Lebanese Middle Eastern Halal Food | Mediterranean Restaurant in Mission Viejo, CA",
    "10e Restaurant",
    "YAYA's Pizza and Mediterranean Grill",
    "Crimson Coward",
    "Calf & Chick",
    "Cedar's Tacos",
    "Dogs Chicks",
    "Dog Chicks",
    "Kabob Cafe",
    "Pizza Corner",
    "URBAN PUNJAB The Royal Kitchen",
    "Win Thai Cuisine Restaurant",
    "AMMATOLI mediterranean bites",
    "Open Sesame",
    "Pho REDBO",
    "Zesty Olives Mediterranean Grill - Irvine",
    "Fatima’s Grill LBC",
    "Fatimas Grill Montebello",
    "Thai Pepper Restaurant",
    "Fatimas Grill",
    "The Red Chickz",
    "Ike's Love & Sandwiches",
    "Barbonzai Lebanese Eatery (Lake Forest)",
    "Barbonzai Lebanese Eatery",
    "H&H Brazilian Steakhouse",
    "H&H Brazilian Steakhouse",
    "Dave's Hot Chicken",
    "Papi Tacos & Churros",
    "Papi Tacos & Churros",
    "Pizza Amore Cafe",
    "Barakah Cafe",
    "Wagyu Shawarma Grill Mission Valley",
    "Dave's Hot Chicken",
    "Dave's Hot Chicken",
    "Dave's Hot Chicken",
    "Dave's Hot Chicken",
    "Dave's Hot Chicken",
    "Olyvoyl Bread & Grill",
    "Shawarma Loca",
    "Ikram Grill",
    "I Can Barbecue Korean Grill-Tustin",
    "Bred's Nashville Hot Chicken",
    "Rotana Alsham Shawarma",
    "Bahar Restaurant",
    "Shawarma Beasts Food Truck",
    "Qamaria Yemeni Coffee Co.",
    "Habibi's Hot Chicken",
    "Habibi's Hot Chicken",
    "Navroz Mediterranean Grill",
    "Taco 900",
    "Desi Cafe",
    "La Carniceria Wagyu",
    "Krispi Hot Chicken",
    "Simpang Asia",
    "Chris N Eddy’s",
    "Aroma Pizza and Pasta",
    "Dave's Hot Chicken",
    "The Halal Guys",
    "DonerG Turkish & Mediterranean Grill - Irvine",
    "DonerG Turkish & Mediterranean Grill - Anaheim",
    "Angry Chickz",
    "Spice Social",
    "Fatima's Grill Garden Grove",
    "Aria Kitchen",
    "Darya",
    "Bunnye Cafe",
    "Halaloğlu",
    "Dizzy Bird",
    "Dave's Hot Chicken",
    "Shamshiri Glendale",
    "Aleppo's Kitchen - Anaheim",
    "Heaven on a Fork",
    "Bread Breakers Deli House",
    "TASA2GO",
    "Tacos El Bandido Express",
    "Zach’s Chicken",
    "Zach’s Chicken",
    "Vito's Italian Pizza",
    "Ike's Love & Sandwiches",
    "疆来MA'S KITCHEN",
    "The Halal Guys",
    "The golden eatery",
    "Gully Burger",
    "The Red Chickz",
    "Le Doner Kebab",
    "Abu Omar Halal",
    "Pita Pita",
    "Ike's Love & Sandwiches",
    "En Familia Restaurant",
    "Shor",
    "CHARMINAR INDIAN RESTAURANT & CATERING | ORANGE COUNTY",
    "Burger Boss",
    "Kebab Planet",
    "Mauza Main Street Deli",
    "Super Dumpling",
    "New York Chicken & Gyro",
    "New York Chicken & Gyro",
    "New York Chicken & Gyro",
    "INC Coffee Roasters",
    "INC Coffee Roasters",
    "Brother’s Juicery",
    "Skewer",
    "Sana’a Cafe",
    "FireFly Burger",
    "Biryani Pot Express",
    "Karak House Coffee Co | Tea & Chai Shop | Pastries and Desserts in Laguna Hills, CA",
    "La Carniceria Wagyu - Costa Mesa",
    "Sababa Falafel Shop",
    "Taka Taka Tacos",
    "Bubba's Tacos",
    "Oliva",
    "Blossom Bites & Eatery",
    "Chargha House",
    "Finjan Coffee Co.",
    "Wet Tacos",
    "HiHo Cheeseburger",
    "Fuze Pizza",
    "Nice Guys Burgers",
    "Omar's Kitchen",
    "The Burger Joint and Brew",
    "Pepz Pizza & Eatery",
    "Byrd's Hot Chicken",
    "Dizzy Bird",
    "Kickin' Fish and Chicken",
    "ZOOD",
    "BiG AL’S Pizzeria",
    "Halal Kabob House",
    "Dimassi's Mediterranean Buffet",
    "Biryani Boys, Modern Pakistani Food"
  ];

  module.exports = restaurantNames;